// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vosjwmlotqvqqrfoxymn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvc2p3bWxvdHF2cXFyZm94eW1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MjcyOTEsImV4cCI6MjA3MDEwMzI5MX0.d95HiySjGprLfd2QON95-Mr4Zoi1xF6haWvX75v7Dx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});